"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { readBetaProfile, type BetaProfile } from "@/lib/beta-profile";
import "../inscription/profile.css";

type ProductResult={title:string;description:string;url:string;merchant:{id:string;name:string;tier:string};directMerchantLink:boolean};

export default function ShoppingPage(){
 const [p,setP]=useState<BetaProfile>({});const [results,setResults]=useState<ProductResult[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [searched,setSearched]=useState(false);
 useEffect(()=>setP(readBetaProfile()),[]);
 async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setLoading(true);setSearched(false);const fd=new FormData(e.currentTarget);const payload={query:String(fd.get("query")||""),tier:String(fd.get("tier")||"balance"),maxPrice:Number(fd.get("maxPrice")||p.budget||200),topSize:p.topSize,bottomSize:p.bottomSize,shoeSize:p.shoeSize,brands:p.brands||[],limit:12};try{const res=await fetch("/api/commerce/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Recherche impossible");setResults(data.results||[]);setSearched(true)}catch(err){setResults([]);setError(err instanceof Error?err.message:"Recherche impossible")}finally{setLoading(false)}}
 return <main className="profile-page"><header className="profile-header"><Link href="/" className="profile-logo">LOOK&GO</Link><span>PIÈCE MANQUANTE · P2</span></header><section className="profile-layout"><div className="profile-intro"><p className="profile-eyebrow">SHOPPING UTILE</p><h1>Trouver seulement <em>la pièce qui manque.</em></h1><p>Look&Go recherche sur des marchands identifiés et renvoie le lien réel de la page trouvée. Les tailles, prix et stocks restent toujours à vérifier chez le marchand.</p><div className="profile-required">Votre profil : haut {p.topSize||"—"} · bas {p.bottomSize||"—"} · pointure {p.shoeSize||"—"} · budget {p.budget||"—"} €</div></div><form className="profile-form" onSubmit={search}><div className="field"><label>Que recherchez-vous ?</label><input name="query" required placeholder="Ex. blazer noir cintré, robe cérémonie rose…"/></div><div className="field"><label>Direction</label><select name="tier" defaultValue={(p.budgetMode||"Équilibre").toLowerCase()==="signature"?"signature":(p.budgetMode||"").toLowerCase()==="smart"?"smart":"balance"}><option value="signature">Signature</option><option value="balance">Équilibre</option><option value="smart">Smart</option></select></div><div className="field"><label>Budget maximum</label><div className="unit-input"><input name="maxPrice" type="number" min="10" max="10000" defaultValue={p.budget||200}/><span>€</span></div></div><button className="profile-submit" disabled={loading}>{loading?"Recherche des marchands…":"Chercher les pièces →"}</button>{error&&<div className="profile-required">{error}</div>}<p className="profile-truth">Aucun prix, stock ou disponibilité n’est inventé par Look&Go. Les résultats viennent d’une recherche web live et les liens pointent directement vers les domaines marchands autorisés.</p></form></section><section style={{width:"min(1180px,calc(100% - 40px))",margin:"0 auto 100px",display:"grid",gap:14}}>{results.map(r=><article key={r.url} style={{border:"1px solid rgba(255,255,255,.14)",padding:24,background:"rgba(255,255,255,.04)"}}><span style={{fontSize:11,letterSpacing:".12em"}}>{r.merchant.name.toUpperCase()} · {r.merchant.tier.toUpperCase()}</span><h2 style={{fontFamily:"var(--font-serif)",fontWeight:400,fontSize:32,margin:"10px 0"}}>{r.title}</h2><p>{r.description}</p><a className="profile-submit" href={r.url} target="_blank" rel="noopener noreferrer nofollow">Voir chez {r.merchant.name} →</a></article>)}{searched&&!results.length&&!error&&<div className="profile-required">Aucune page marchande suffisamment pertinente n’a été trouvée. Essayez une description plus simple ou une autre direction.</div>}</section></main>;
}
