import Link from "next/link";
import "../profile.css";
import "./analyse.css";

const looks=[
 {name:"SIGNATURE",price:"≈ 450 €+",text:"Pièces premium et fortes, avec priorité au style et à la qualité perçue.",tone:"sig"},
 {name:"ÉQUILIBRE",price:"≈ 180–250 €",text:"Une composition maîtrisée avec un bon équilibre entre allure, qualité et budget.",tone:"bal"},
 {name:"SMART",price:"≈ 80–120 €",text:"Une version accessible, pensée pour conserver l’intention du look avec un budget serré.",tone:"sma"},
];

export default function AnalyseStep(){
 return <main className="analysis-page"><header className="profile-header"><Link href="/" className="profile-logo">LOOK&GO</Link><span>ANALYSE & PREMIER LOOK · 03/03</span></header><section className="analysis-shell"><div className="analysis-hero"><p className="profile-eyebrow">VOTRE PROFIL EST PRÊT</p><h1>Maintenant, Look&Go transforme vos préférences en <em>looks concrets.</em></h1><p>Cette étape présente le fonctionnement cible : morphologie, colorimétrie, style et budget sont combinés pour construire trois propositions cohérentes.</p></div><div className="analysis-grid"><article><span>01</span><strong>Morphologie</strong><p>Les proportions servent à filtrer coupes, volumes et longueurs pertinentes.</p></article><article><span>02</span><strong>Colorimétrie</strong><p>Cheveux, portrait et préférences couleurs guident les harmonies proposées.</p></article><article><span>03</span><strong>Style</strong><p>Vos goûts et marques préférées donnent la direction créative.</p></article><article><span>04</span><strong>Budget</strong><p>Chaque look est ensuite décliné en trois niveaux de prix.</p></article></div><div className="result-head"><div><p className="profile-eyebrow">VOS 3 PREMIÈRES DIRECTIONS</p><h2>Un style.<br/><em>Trois budgets.</em></h2></div><p>Les montants ci-dessous sont uniquement des repères de démonstration. En production, chaque carte sera calculée à partir de vrais produits, vrais prix et catalogues marchands connectés.</p></div><div className="result-grid">{looks.map(l=><article className={`result-card ${l.tone}`} key={l.name}><span className="result-kicker">LOOK INITIAL</span><h3>{l.name}</h3><div className="result-price">{l.price}</div><p>{l.text}</p><div className="result-tags"><span>Votre style</span><span>Vos couleurs</span><span>Votre taille</span></div><button disabled>Voir les produits réels bientôt</button></article>)}</div><div className="analysis-final"><div><span>PROCHAINE ÉTAPE PRODUIT</span><p>Connecter les catalogues marchands et le moteur Try-On pour remplacer cette démonstration par vos premières vraies tenues achetables.</p></div><Link href="/#shopping">Découvrir les 3 budgets <span>→</span></Link></div><p className="analysis-truth">Démo UI : aucune analyse biométrique, morphologique ou colorimétrique réelle n’est exécutée sur cette page actuellement.</p></section></main>
}
