"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {readBetaProfile} from "@/lib/beta-profile";
import "./settings.css";

type Provider={id:string;label:string;enabled:boolean;configured:boolean;capabilities:string[]};
const ADMIN="rigahludovic@gmail.com";
export default function SettingsPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [providers,setProviders]=useState<Provider[]>([]);const [keys,setKeys]=useState<Record<string,string>>({});const [saving,setSaving]=useState<string|null>(null);const [testing,setTesting]=useState<string|null>(null);const [message,setMessage]=useState("");const [canManage,setCanManage]=useState(false);const [adminEmail,setAdminEmail]=useState("");
 async function load(email:string){const r=await fetch("/api/admin/ai",{headers:{"x-lookgo-admin-email":email},cache:"no-store"});const d=await r.json();if(r.ok){setProviders(d.providers||[]);setCanManage(Boolean(d.canManage));}else setMessage(d.error||"Impossible de charger la configuration.");}
 useEffect(()=>{const email=(readBetaProfile().email||"").trim().toLowerCase();const ok=email===ADMIN;setAdminEmail(email);setAllowed(ok);if(ok)load(email).catch(()=>setMessage("Impossible de charger la configuration."));},[]);
 function patchProvider(id:string,patch:Partial<Provider>){setProviders(items=>items.map(p=>p.id===id?{...p,...patch}:p));}
 async function saveProvider(p:Provider){setSaving(p.id);setMessage("");try{const r=await fetch("/api/admin/ai",{method:"POST",headers:{"Content-Type":"application/json","x-lookgo-admin-email":adminEmail},body:JSON.stringify({action:"save",provider:p.id,enabled:p.enabled,apiKey:keys[p.id]||""})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Échec de l’enregistrement.");setKeys(k=>({...k,[p.id]:""}));setMessage(d.message||"Configuration enregistrée.");setTimeout(()=>load(adminEmail),1500);}catch(e){setMessage(e instanceof Error?e.message:"Échec de l’enregistrement.");}finally{setSaving(null);}}
 async function testProvider(p:Provider){setTesting(p.id);setMessage("");try{const r=await fetch("/api/admin/ai",{method:"POST",headers:{"Content-Type":"application/json","x-lookgo-admin-email":adminEmail},body:JSON.stringify({action:"test",provider:p.id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Test de connexion impossible.");setMessage(d.message||"Connexion valide.");}catch(e){setMessage(e instanceof Error?e.message:"Test de connexion impossible.");}finally{setTesting(null);}}
 if(allowed===null)return <main className="settings-page"><p>Vérification…</p></main>;
 if(!allowed)return <main className="settings-page"><section className="settings-denied"><span>ACCÈS ADMIN</span><h1>Accès réservé.</h1><p>Cette console est disponible uniquement pour l’administrateur Look&Go.</p><Link href="/profil">Retour au profil</Link></section></main>;
 return <main className="settings-page"><header><Link href="/profil">← Profil</Link><strong>LOOK&GO · ADMIN</strong></header><section className="settings-shell"><p className="eyebrow">CENTRE DE CONTRÔLE IA</p><h1>Moteurs & routage</h1><p className="intro">Activez ou désactivez chaque moteur, remplacez une clé API et testez la connexion sans afficher le secret.</p>{message&&<div className="settings-message">{message}</div>}{!canManage&&<div className="settings-warning"><strong>Une dernière configuration est requise</strong><p>Les champs sont bien modifiables, mais Look&Go ne peut pas encore écrire dans les variables Vercel. Ajoutez une seule fois <code>VERCEL_TOKEN</code> dans les variables d’environnement du projet. Ensuite revenez ici et rechargez la page.</p><a href="https://vercel.com/rigahludovic-7554s-projects/look-go/settings/environment-variables" target="_blank" rel="noreferrer">Ouvrir les variables Vercel →</a></div>}<div className="provider-grid">{providers.map(p=><article className="provider-card" key={p.id}><div className="provider-top"><div><span>{p.configured?"CONFIGURÉ":"CLÉ MANQUANTE"}</span><h2>{p.label}</h2></div><label className="switch"><input type="checkbox" checked={p.enabled} onChange={e=>patchProvider(p.id,{enabled:e.target.checked})}/><i></i><b>{p.enabled?"ACTIVÉ":"DÉSACTIVÉ"}</b></label></div><div className="caps">{p.capabilities.map(c=><span key={c}>{c}</span>)}</div><label className="key-field">Nouvelle clé API<input type="password" value={keys[p.id]||""} onChange={e=>setKeys(k=>({...k,[p.id]:e.target.value}))} autoComplete="new-password" placeholder={p.configured?"Laisser vide pour conserver la clé actuelle":"Coller la clé API"}/></label><p>{p.enabled?"Le routeur pourra utiliser ce moteur s’il possède une clé valide.":"Le routeur ignorera ce moteur."}</p><div className="provider-actions"><button className="save-provider" type="button" disabled={saving===p.id} onClick={()=>saveProvider(p)}>{saving===p.id?"Enregistrement…":canManage?"Enregistrer & appliquer":"Tester l’enregistrement"}</button><button className="test-provider" type="button" disabled={testing===p.id||!p.configured} onClick={()=>testProvider(p)}>{testing===p.id?"Test…":"Tester la connexion"}</button></div></article>)}</div><section className="routing"><h2>Ordre de secours</h2><div><strong>Image / Try-On</strong><p>OpenAI → Google → Higgsfield</p></div><div><strong>Vidéo</strong><p>Higgsfield → Google → OpenAI</p></div><div><strong>Styliste</strong><p>Claude → OpenAI → Google</p></div><small>Seuls les moteurs activés, configurés et compatibles seront utilisés. Après une modification, Look&Go lance automatiquement un redéploiement de production pour appliquer les nouveaux secrets.</small></section></section></main>}
