import { NextResponse } from "next/server";
import { buildAiCostMeta } from "@/lib/ai/costs";

export const runtime="nodejs";
export const maxDuration=60;
const TIERS=new Set(["signature","balance","smart"]);
const TIMEOUT_MS=25_000;

function runwayPrompt(tier:string){const label=tier==="signature"?"Signature":tier==="smart"?"Smart":"Équilibre";return [`Create a realistic vertical fashion runway clip for the ${label} Look&Go look using the supplied image as the exact visual reference and starting frame.`,"Preserve the same adult person's facial identity, skin tone, hairstyle, apparent age, body proportions, morphology and outfit exactly as shown in the reference image.","Do not beautify, slim, enlarge, reshape, de-age or replace the person. Do not redesign, recolor or swap the clothing.","Motion should be restrained and physically natural: a slow confident walk forward, subtle fabric movement, then a gentle 30 to 45 degree turn.","Keep the full body visible from head to shoes. Stable premium editorial lighting, clean fashion-studio background, realistic anatomy, no camera warping, no sudden cuts.","The clip is a fashion visualization. Prioritize identity and outfit continuity over dramatic motion."].join(" ")}
function normalizeReference(image:File){if(!["image/jpeg","image/png","image/webp"].includes(image.type))throw new Error("FORMAT_IMAGE");return image}
async function timedFetch(url:string,init:RequestInit){const c=new AbortController();const timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(timer)}}

export async function POST(request:Request){
 const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:"Le moteur vidéo n'est pas configuré sur le serveur."},{status:503});
 const started=Date.now();
 try{const incoming=await request.formData();const rawImage=incoming.get("image");const tier=String(incoming.get("tier")||"").toLowerCase();if(!(rawImage instanceof File))return NextResponse.json({error:"Le look Try-On validé est obligatoire."},{status:400});if(!TIERS.has(tier))return NextResponse.json({error:"Niveau de look invalide."},{status:400});if(rawImage.size>15_000_000)return NextResponse.json({error:"L'image Try-On doit faire moins de 15 Mo."},{status:400});const image=normalizeReference(rawImage);const model=process.env.OPENAI_VIDEO_MODEL||"sora-2";const body=new FormData();body.append("model",model);body.append("prompt",runwayPrompt(tier));body.append("seconds",process.env.OPENAI_VIDEO_SECONDS||"8");body.append("size","720x1280");body.append("input_reference",image,image.name||`${tier}-runway.jpg`);const response=await timedFetch("https://api.openai.com/v1/videos",{method:"POST",headers:{Authorization:`Bearer ${key}`},body});const data=await response.json().catch(()=>({}));if(!response.ok){const providerMessage=String(data?.error?.message||"");console.error("OpenAI video create failed",response.status,providerMessage||data);const quota=response.status===429;return NextResponse.json({error:quota?"Les crédits vidéo sont temporairement épuisés.":providerMessage?`Création vidéo refusée : ${providerMessage}`:"La création du défilé a échoué. Réessayez dans quelques instants."},{status:quota?429:502})}const meta=buildAiCostMeta("openai",model,"video",Date.now()-started);console.info("RUNWAY_CREATE_SUCCESS",JSON.stringify({tier,id:data.id,...meta}));return NextResponse.json({id:data.id,status:data.status,progress:data.progress??0,tier,meta})}catch(error){if(error instanceof Error&&error.name==="AbortError")return NextResponse.json({error:"Le moteur vidéo met trop de temps à répondre. Réessayez."},{status:504});console.error("Runway create route error",error);return NextResponse.json({error:"Erreur serveur pendant la création du défilé."},{status:500})}
}

export async function GET(request:Request){const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:"Le moteur vidéo n'est pas configuré."},{status:503});const id=new URL(request.url).searchParams.get("id")||"";if(!/^video_[A-Za-z0-9_-]+$/.test(id))return NextResponse.json({error:"Identifiant vidéo invalide."},{status:400});try{const response=await timedFetch(`https://api.openai.com/v1/videos/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${key}`},cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)return NextResponse.json({error:"Impossible de récupérer l'état du défilé."},{status:502});return NextResponse.json({id:data.id,status:data.status,progress:data.progress??0,error:data.error?.message||null})}catch(error){if(error instanceof Error&&error.name==="AbortError")return NextResponse.json({error:"Le suivi vidéo met trop de temps à répondre."},{status:504});console.error("Runway status route error",error);return NextResponse.json({error:"Erreur pendant le suivi du défilé."},{status:500})}}
