import Image from "next/image";
import Link from "next/link";
import { TryOnDemo } from "@/components/TryOnDemo";
import { BudgetLooks } from "@/components/BudgetLooks";
import { Plans } from "@/components/Plans";
import "./v31.css";
import "./brand.css";

const editorialImages={vibrantWoman:"https://images.unsplash.com/photo-1776790376541-233f911d90b4?auto=format&fit=crop&w=1600&q=88",jewelryWoman:"https://images.unsplash.com/photo-1767249629217-536a5ef26cc2?auto=format&fit=crop&w=1600&q=88",blueSuitMan:"https://images.unsplash.com/photo-1754485115876-9221149ccc19?auto=format&fit=crop&w=1600&q=88"};

export default function HomePage(){return <main>
<header className="site-header"><Link href="#top" className="brand-lockup" aria-label="Look&Go, accueil"><Image src="/lookgo-logo.svg" alt="" width={720} height={180} priority className="brand-logo"/></Link><nav className="desktop-nav"><Link href="#shopping">3 budgets</Link><Link href="#try-on">Try-On</Link><Link href="#styliste">Styliste</Link><Link href="#mariage">Mariage</Link><Link href="#offres">Offres</Link></nav><div className="header-actions"><Link href="/connexion?mode=register" className="text-link">Accès bêta</Link><Link href="/connexion?mode=register" className="button button-small button-dark">Trouver mon style</Link></div></header>
<section id="top" className="hero section-shell"><div className="hero-copy"><div className="v3-pill">VOTRE PERSONAL SHOPPER IA</div><h1>N’achetez plus un vêtement.<br/><em>Achetez celui qui vous va.</em></h1><p className="hero-intro">Look&Go apprend votre style, votre morphologie, vos couleurs, votre dressing et votre budget. Découvrez des looks pensés pour vous et visualisez-les sur vous avant de décider.</p><div className="cta-row"><Link href="/connexion?mode=register" className="button button-coral">Trouver ce qui me va</Link><Link href="#motion" className="button button-ghost">Comment ça marche</Link></div><div className="color-signals"><span>1 PROFIL</span><span>3 BUDGETS</span><span>3 + 3 LOOKS</span><span>TRY-ON IA</span></div></div><div className="hero-visual"><div className="hero-sun"/><TryOnDemo/><div className="hero-sticker">VOIR<br/>SUR MOI</div></div></section>
<section className="marquee" aria-hidden="true"><div>SMART · ÉQUILIBRE · SIGNATURE · VOIR SUR MOI · CHOISIR MIEUX · PERSONAL SHOPPER · SMART · ÉQUILIBRE · SIGNATURE ·</div></section>
<BudgetLooks/>
<section id="motion" className="motion-story"><div className="motion-story-inner"><div className="motion-head"><div><p className="eyebrow eyebrow-light">COMMENT ÇA MARCHE</p><h2>Vous.<br/><em>Puis les vêtements.</em></h2></div><div><p>Une boutique commence par son catalogue. Look&Go commence par vous. Votre profil devient le fil conducteur de vos recommandations, même lorsque vous changez de marque ou de budget.</p></div></div><div className="motion-track"><article className="motion-card"><div className="motion-dot"/><span>01 · VOUS</span><h3>Portrait, silhouette, tailles.</h3><p>Votre identité visuelle et vos proportions guident le Try-On.</p></article><article className="motion-card"><div className="motion-dot"/><span>02 · VOTRE STYLE</span><h3>24 univers, vêtements, couleurs.</h3><p>Robe, jupe, body, pantalon, short, costume, streetwear, chic, glamour et bien plus.</p></article><article className="motion-card"><div className="motion-dot"/><span>03 · VOS CHOIX</span><h3>3 looks + 3 alternatives.</h3><p>Signature, Équilibre et Smart, puis trois nouvelles idées sans tourner toujours autour de la même silhouette.</p></article><article className="motion-card"><div className="motion-dot"/><span>04 · SUR VOUS</span><h3>Visualisez avant de décider.</h3><p>Le Try-On IA vous aide à vous projeter avant de passer chez le marchand.</p></article></div></div></section>
<section id="try-on" className="section section-shell split-section colorful-split"><div className="section-kicker">TRY-ON IA</div><div className="section-copy-large"><h2>Ce n’est pas un mannequin.<br/><em>C’est vous.</em></h2><p>Votre portrait sert de référence d’identité et votre photo plein pied de référence morphologique. L’objectif : préserver votre apparence pour vous permettre de juger le style sur la bonne personne.</p><Link href="/connexion?mode=register" className="button button-coral">Voir un look sur moi</Link></div><div className="editorial-image editorial-image-tall image-frame-coral"><Image src={editorialImages.vibrantWoman} alt="Portrait mode naturel d’une femme noire portant une tenue colorée" fill sizes="(max-width:768px) 100vw,42vw"/></div></section>
<section id="styliste" className="section stylist-section colorful-stylist"><div className="section-shell stylist-grid"><div className="stylist-heading"><p className="eyebrow">PERSONAL SHOPPER</p><h2>Pourquoi Look&Go<br/><em>avant la boutique ?</em></h2></div><div className="stylist-conversation"><p>« Je veux une robe qui fonctionne avec ma morphologie. »</p><p>« Donne-moi le même esprit sous 150 €. »</p><p>« J’ai déjà trois pantalons noirs : propose autre chose. »</p><p>« Utilise ma veste et complète ma tenue. »</p></div><p className="statement-line">Les marchands vendent leurs vêtements. <strong>Look&Go vous aide à choisir les bons.</strong> Votre profil, vos préférences et votre dressing restent le centre de la décision.</p></div></section>
<section className="identity-section"><div className="identity-photo"><Image src={editorialImages.jewelryWoman} alt="Portrait éditorial naturel d’une femme noire" fill sizes="(max-width:768px) 100vw,48vw"/></div><div className="identity-copy"><p className="eyebrow eyebrow-light">VOTRE PROFIL VOUS SUIT</p><h2>Changez de boutique.<br/>Pas de styliste.</h2><div className="you-word">Vous.</div><p>Smart aujourd’hui, Signature pour une cérémonie : Look&Go garde votre style, vos couleurs, votre budget et progressivement votre dressing comme référence.</p></div></section>
<section id="mariage" className="section personalization-section"><div className="section-shell personalization-inner"><div className="personalization-copy"><p className="eyebrow">NOUVEAU · MON MARIAGE</p><h2>Un Wedding Stylist IA.<br/><em>Pour tout votre univers.</em></h2><p>Créez la charte de votre mariage — thème, couleurs, dress code, budgets — puis coordonnez mariée, marié, témoins et cortège avec des profils et Try-On individuels.</p><div className="personalization-tags">{['THÈME','COULEURS','MARIÉE','MARIÉ','TÉMOINS','CORTÈGE','3 + 3 LOOKS'].map(x=><span key={x}>{x}</span>)}</div><Link href="#offres" className="button button-dark">Découvrir les packs Mariage</Link></div><div className="editorial-image personalization-image image-frame-cobalt"><Image src={editorialImages.blueSuitMan} alt="Homme noir dans une tenue bleu cobalt" fill sizes="(max-width:768px) 100vw,42vw"/></div></div></section>
<Plans/>
<section id="commencer" className="final-cta"><div className="final-orb final-orb-one"/><div className="final-orb final-orb-two"/><div className="section-shell final-cta-inner"><p className="eyebrow">LOOK&GO</p><h2>Votre style.<br/><em>Avant votre panier.</em></h2><p>Commencez gratuitement. Les bêta-testeurs disposent d’un accès étendu aux fonctionnalités disponibles et aux nouveautés.</p><Link href="/connexion?mode=register" className="button button-light">Créer mon profil</Link><span>Les achats restent réalisés auprès des marchands lorsque leurs liens réels sont disponibles.</span></div></section>
<footer className="site-footer section-shell"><div><Image src="/lookgo-logo.svg" alt="Look&Go" width={720} height={180} className="footer-brand-logo"/><p>Your style. Your fit. Your choice.</p></div><nav><Link href="#shopping">3 budgets</Link><Link href="#try-on">Try-On</Link><Link href="#mariage">Mariage</Link><Link href="#offres">Offres</Link></nav><p className="footer-note">Look&Go distingue les fonctionnalités disponibles, en test et à venir. Aucun partenariat, stock, prix marchand ou commission n’est inventé.</p></footer>
</main>}
