"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { readBetaProfile, saveBetaProfile, type BetaProfile } from "@/lib/beta-profile";
import { betaAuthStatus, createOrUpdateBetaAccessCode, readBetaProfileCloud, saveBetaProfileCloud, signInBetaWithCode } from "@/lib/firebase-beta";
import { firebaseConfigStatus } from "@/lib/firebase-client";
import "./auth.css";

function hasIdentity(profile:BetaProfile){return Boolean(profile.email||profile.pseudo)}
function nextBetaPath(profile:BetaProfile){if(profile.complete)return "/profil";const ready=Boolean(profile.email&&profile.pseudo&&profile.height&&profile.weight&&profile.age&&profile.portraitName&&profile.fullName);return ready?"/inscription/style":"/inscription"}
function trace(event:string,detail:Record<string,unknown>={}){void fetch("/api/client-telemetry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event,detail}),keepalive:true}).catch(()=>{});}
function traceFirebaseConfig(){const status=firebaseConfigStatus();if(!status.ready)trace("firebase_client_config_missing",{missing:status.missing});return status;}

export default function ConnexionPage(){
 const router=useRouter();const [error,setError]=useState("");const [checking,setChecking]=useState(true);const [mode,setMode]=useState<"new"|"return">("new");const [working,setWorking]=useState(false);
 useEffect(()=>{let alive=true;(async()=>{const local=readBetaProfile();let cloud:BetaProfile|null=null;try{cloud=await readBetaProfileCloud();}catch{}if(!alive)return;const merged={...(cloud||{}),...local};const auth=await betaAuthStatus();if(hasIdentity(merged)&&(auth.durable||Object.keys(local).length>0)){saveBetaProfile({...merged,codeConfigured:auth.accessCodeEnabled||merged.codeConfigured});trace("beta_access_session_restored",{durable:auth.durable,accessCodeEnabled:auth.accessCodeEnabled});router.replace(nextBetaPath(merged));return;}setChecking(false);})();return()=>{alive=false};},[router]);
 async function startBeta(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError("");setWorking(true);const fd=new FormData(e.currentTarget);const email=String(fd.get("email")||"").trim().toLowerCase();const name=String(fd.get("name")||"").trim();const code=String(fd.get("code")||"").trim();const confirm=String(fd.get("confirmCode")||"").trim();
  if(!name){setError("Entrez votre prénom ou pseudo.");setWorking(false);return}if(!email.includes("@")){setError("Entrez une adresse email valide.");setWorking(false);return}if(!/^\d{6}$/.test(code)){setError("Choisissez un code personnel de 6 chiffres.");setWorking(false);return}if(code!==confirm){setError("Les deux codes personnels ne correspondent pas.");setWorking(false);return}
  trace("beta_access_creation_started");traceFirebaseConfig();
  const access=await createOrUpdateBetaAccessCode(email,code);
  if(!access.ok){setError(access.error||"Impossible de créer votre code personnel.");setWorking(false);trace("beta_access_creation_failed",{reason:access.error||"unknown"});return}
  const profile:BetaProfile={email,pseudo:name,complete:false,codeConfigured:true};saveBetaProfile(profile);const cloudOk=await saveBetaProfileCloud(profile);
  if(!cloudOk){setError("Votre accès est créé, mais votre profil n’a pas encore pu être synchronisé. Réessayez avant de continuer.");setWorking(false);trace("beta_profile_initial_sync_failed");return}
  trace("beta_access_creation_success");router.push("/inscription");
 }
 async function recover(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError("");setWorking(true);const fd=new FormData(e.currentTarget);const email=String(fd.get("email")||"").trim().toLowerCase();const code=String(fd.get("code")||"").trim();trace("beta_access_recovery_started");traceFirebaseConfig();
  const result=await signInBetaWithCode(email,code);if(!result.ok){setError(result.error||"Connexion impossible.");setWorking(false);trace("beta_access_recovery_failed",{reason:result.error||"unknown"});return}
  if(!result.profile||!hasIdentity(result.profile)){setError("Votre accès est reconnu, mais votre profil n’a pas pu être restauré. Réessayez dans quelques instants.");setWorking(false);trace("beta_access_recovery_profile_missing");return}
  const profile={...result.profile,email,codeConfigured:true};saveBetaProfile(profile);setWorking(false);trace("beta_access_recovery_success",{complete:Boolean(profile.complete)});router.replace(nextBetaPath(profile));
 }
 if(checking)return <main className="auth-page"><section className="auth-shell"><div className="auth-panel"><p className="auth-privacy">Recherche de votre espace Look&Go…</p></div></section></main>;
 return <main className="auth-page"><header className="auth-header"><Link href="/" className="auth-logo">LOOK&GO</Link><Link href="/">Retour au site</Link></header><section className="auth-shell"><div className="auth-story"><p>BÊTA PRIVÉE LOOK&GO</p><h1>Votre dressing <em>vous reconnaît.</em></h1><span>Votre profil est créé une seule fois. Votre email et votre code personnel permettent ensuite de retrouver le même espace, les photos et l’historique sur un autre appareil.</span></div><div className="auth-panel"><div className="auth-tabs"><button className={mode==="new"?"active":""} type="button" onClick={()=>{setMode("new");setError("")}}>Nouvel accès</button><button className={mode==="return"?"active":""} type="button" onClick={()=>{setMode("return");setError("")}}>Retrouver mon espace</button></div>{mode==="new"?<form onSubmit={startBeta}><label>Prénom ou pseudo<input name="name" required minLength={2} placeholder="Votre prénom ou pseudo" autoComplete="nickname"/></label><label>Email<input name="email" type="email" required autoComplete="email" placeholder="vous@exemple.fr"/></label><label>Créer mon code personnel<input name="code" type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="new-password" placeholder="6 chiffres"/></label><label>Confirmer mon code<input name="confirmCode" type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="new-password" placeholder="6 chiffres"/></label><p className="auth-privacy">Gardez ce code : il permet de retrouver votre espace sur un autre téléphone sans recevoir d’email.</p>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" type="submit" disabled={working}>{working?"Création…":"Démarrer mon test →"}</button></form>:<form onSubmit={recover}><label>Email utilisé sur Look&Go<input name="email" type="email" required autoComplete="email" placeholder="vous@exemple.fr"/></label><label>Code personnel<input name="code" type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="current-password" placeholder="6 chiffres"/></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" type="submit" disabled={working}>{working?"Connexion…":"Retrouver mon espace →"}</button><p className="auth-privacy">Vous aviez déjà commencé la bêta avant l’arrivée du code ? Sur l’appareil où votre profil est encore reconnu, ouvrez « Mon profil » puis créez votre code. Votre profil, vos photos et vos looks existants restent conservés.</p></form>}<p className="auth-privacy">Sur votre appareil habituel, Look&Go reprend automatiquement une session déjà enregistrée.</p></div></section></main>;
}
