"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";

const closet="https://images.unsplash.com/photo-1520923179278-ee25e25e09e4?auto=format&fit=crop&w=1800&q=88";
const work="https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=1200&q=88";
const casual="https://images.unsplash.com/photo-1780566759959-73ce2af09f7c?auto=format&fit=crop&w=1200&q=88";
const evening="https://images.unsplash.com/photo-1674466922242-793e4092a9e2?auto=format&fit=crop&w=1200&q=88";
const tryon="https://images.unsplash.com/photo-1729202305341-d146fdea0a03?auto=format&fit=crop&w=1400&q=88";
const Icon=({name}:{name:string})=><span className={`v2-icon i-${name}`} aria-hidden="true"/>;

function Header(){return <header className="v2-header"><Link href="#top" className="v2-logo"><Image src="/lookgo-logo.svg" alt="Look&Go" width={500} height={125}/></Link><nav><a href="#experience">L’expérience</a><a href="#dressing">Dressing</a><a href="#tryon">Try-On</a><a href="#offers">Offres</a></nav><Link href="/connexion?mode=register" className="v2-header-cta">Scanner mon dressing <span>→</span></Link></header>}

function Hero(){return <section id="top" className="v2-hero"><div className="v2-hero-bg"><Image src={closet} alt="Penderie remplie de vêtements" fill priority sizes="100vw"/></div><div className="v2-shade"/><div className="v2-scan-beam"/><div className="v2-detect d1"><span>Veste</span><b>98%</b></div><div className="v2-detect d2"><span>Chemise</span><b>96%</b></div><div className="v2-detect d3"><span>Pantalon</span><b>94%</b></div><div className="v2-hero-content"><span className="v2-overline">LOOK&GO · LE DRESSING PRIVÉ IA</span><h1>Votre dressing<br/><em>vous connaît enfin.</em></h1><p>Photographiez votre penderie. Look&Go reconnaît vos vêtements, vous les fait valider puis imagine des tenues avec ce que vous possédez déjà.</p><div className="v2-actions"><Link href="#experience" className="v2-primary">Entrer dans mon dressing <span>→</span></Link><a href="#story" className="v2-secondary">Voir comment ça marche</a></div></div><div className="v2-status"><span><Icon name="scan"/>12 pièces reconnues</span><span><Icon name="spark"/>3 looks prêts</span><span><Icon name="bag"/>0 achat inutile</span></div></section>}

function Story(){return <section id="story" className="v2-story"><div className="v2-story-num">47</div><div><span className="v2-overline dark">LE PARADOXE DU DRESSING</span><h2>47 vêtements.<br/><em>Et toujours cette phrase.</em></h2><blockquote>« Je n’ai rien à me mettre. »</blockquote><p>Look&Go ne commence pas par vous vendre quelque chose. Il commence par révéler ce que vous avez déjà.</p></div></section>}

function Experience(){const [step,setStep]=useState(0);const steps=[{n:"01",icon:"camera",title:"Je photographie",text:"Une photo de votre vraie penderie suffit pour commencer.",label:"PHOTO PENDERIE"},{n:"02",icon:"scan",title:"L’IA reconnaît",text:"Les vêtements visibles sont repérés et classés.",label:"12 PIÈCES DÉTECTÉES"},{n:"03",icon:"check",title:"Je valide",text:"Vous confirmez, corrigez ou retirez chaque pièce.",label:"9 VALIDÉES · 3 À VÉRIFIER"},{n:"04",icon:"spark",title:"Je reçois mes looks",text:"Look&Go assemble ensuite vos pièces selon votre journée.",label:"3 LOOKS CRÉÉS"}];return <section id="experience" className="v2-experience"><div className="v2-section-head"><span className="v2-overline">L’EXPÉRIENCE LOOK&GO</span><h2>De votre penderie<br/><em>à votre tenue.</em></h2><p>Chaque étape montre maintenant exactement ce que vous êtes en train de faire.</p></div><div className="v2-exp-shell"><div className="v2-exp-nav">{steps.map((s,i)=><button key={s.n} onClick={()=>setStep(i)} className={i===step?"active":""}><b>{s.n}</b><Icon name={s.icon}/><span>{s.title}</span></button>)}</div><div className="v2-exp-screen"><div className="v2-exp-photo"><Image src={closet} alt={steps[step].title} fill sizes="(max-width:800px) 100vw,55vw"/><div className={`v2-analysis a${step}`}><i/><i/><i/><i/></div><div className="v2-exp-label"><span>LOOK&GO VISION</span><strong>{steps[step].label}</strong></div></div><div className="v2-exp-copy"><span>{steps[step].n} / 04</span><Icon name={steps[step].icon}/><h3>{steps[step].title}</h3><p>{steps[step].text}</p><button onClick={()=>setStep((step+1)%4)}>Étape suivante →</button></div></div></div></section>}

function Wardrobe(){return <section id="dressing" className="v2-wardrobe"><div className="v2-wardrobe-copy"><span className="v2-overline">VOTRE DRESSING, PAS UN CATALOGUE</span><h2>Vos vêtements deviennent<br/><em>une matière à créer.</em></h2><p>L’IA retrouve les associations oubliées, remet les pièces peu portées dans la rotation et identifie ce qui manque vraiment.</p><div className="v2-metrics"><div><strong>34%</strong><span>noir dans votre dressing</span></div><div><strong>8</strong><span>pièces peu portées</span></div><div><strong>3,20€</strong><span>cost-per-wear moyen</span></div></div></div><div className="v2-wardrobe-ui"><div className="v2-ui-top"><span>MON DRESSING</span><b>38 pièces</b></div><div className="v2-clothes"><article><Icon name="hanger"/><b>Vestes</b><span>6 pièces</span></article><article><Icon name="dress"/><b>Robes</b><span>9 pièces</span></article><article><Icon name="shirt"/><b>Hauts</b><span>14 pièces</span></article><article><Icon name="bag"/><b>Accessoires</b><span>9 pièces</span></article></div><div className="v2-insight"><Icon name="spark"/><div><b>Une pièce dort depuis 83 jours.</b><span>Je peux créer 4 looks autour de votre blazer noir.</span></div><button>Créer les looks →</button></div></div></section>}

const looks=[{tag:"LUN · TRAVAIL",title:"Réunion à 10h",score:"94%",img:work},{tag:"VEN · DÎNER",title:"Terrasse à 20h",score:"97%",img:evening},{tag:"SAM · WEEK-END",title:"Déjeuner en ville",score:"91%",img:casual}];
function Looks(){return <section className="v2-looks"><div className="v2-section-head light"><span className="v2-overline dark">VOTRE SEMAINE, DÉJÀ HABILLÉE</span><h2>Pas des inspirations.<br/><em>Vos tenues.</em></h2><p>Trois moments, trois silhouettes différentes. Les visuels servent à montrer le type de résultat attendu du Personal Shopper.</p></div><div className="v2-look-row">{looks.map(x=><article key={x.tag}><div className="v2-look-photo"><Image src={x.img} alt={`${x.title} — exemple de tenue`} fill sizes="(max-width:700px) 82vw,30vw"/><span>{x.tag}</span></div><div><h3>{x.title}</h3><span>Compatibilité style · {x.score}</span><p>3 pièces de votre dressing</p><button>Voir le look →</button></div></article>)}</div></section>}

function TryOn(){return <section id="tryon" className="v2-tryon"><div className="v2-tryon-visual"><div className="v2-before-after"><div className="v2-ba-side"><Image src={tryon} alt="Photo de référence avant Try-On" fill sizes="25vw"/><span>AVANT</span></div><div className="v2-ba-side after"><Image src={tryon} alt="Aperçu après Try-On" fill sizes="25vw"/><span>APERÇU IA</span></div><div className="v2-ba-handle">↔</div></div></div><div className="v2-try-copy"><span className="v2-overline">TRY-ON PRIVÉ</span><h2>La pièce manque ?<br/><em>Voyez-la sur vous.</em></h2><p>Une comparaison avant / aperçu immédiatement compréhensible, avec une personne comme référence plutôt qu’une photo mode générique.</p><ul><li><Icon name="person"/>Morphologie comme référence</li><li><Icon name="face"/>Identité visuelle préservée comme objectif</li><li><Icon name="eye"/>Comparaison claire avant / aperçu</li></ul><small>Les rendus IA restent des aides visuelles. Le résultat réel peut varier selon la photo, la coupe et le vêtement.</small><a href="#offers" className="v2-primary">Découvrir Try-On <span>→</span></a></div></section>}

const offers=[{name:"Découverte",price:"0 €",desc:"Découvrez ce que votre dressing peut déjà faire.",items:["1 scan dressing","5 pièces validées","1 premier look"]},{name:"Pack Looks",price:"9,99 €",desc:"Une occasion. Trois réponses.",items:["3 looks personnalisés","Vos pièces en priorité","Occasion au choix"]},{name:"Premium",price:"9,99 €/mois",desc:"Votre dressing au quotidien.",items:["Dressing étendu","Looks hebdomadaires","Cost-per-wear & insights"],hot:true},{name:"VIP Try-On",price:"24,99 €/mois",desc:"Décidez avec plus de confiance.",items:["Try-On IA selon quotas","Looks avancés","Fonctions premium"]}];
function Offers(){return <section id="offers" className="v2-offers"><div className="v2-section-head"><span className="v2-overline dark">CHOISISSEZ VOTRE EXPÉRIENCE</span><h2>Commencez par votre dressing.<br/><em>Montez en puissance si ça vous aide.</em></h2></div><div className="v2-offer-grid">{offers.map(o=><article key={o.name} className={o.hot?"hot":""}>{o.hot&&<span className="v2-badge">LE CŒUR LOOK&GO</span>}<h3>{o.name}</h3><strong>{o.price}</strong><p>{o.desc}</p><ul>{o.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Link href="/connexion?mode=register">Commencer <span>→</span></Link></article>)}</div><p className="v2-note">Tarifs de lancement à tester pendant la bêta. Les services payants ne sont facturés qu’après leur activation réelle et les quotas IA pourront évoluer selon les coûts mesurés.</p></section>}
function Final(){return <><section className="v2-final"><span className="v2-overline">BÊTA PRIVÉE</span><h2>Ouvrez votre dressing.<br/><em>Look&Go s’occupe du reste.</em></h2><p>Faites partie des premières personnes à construire le Dressing Privé IA.</p><Link href="/connexion?mode=register" className="v2-primary">Demander mon accès <span>→</span></Link></section><footer className="v2-footer"><Image src="/lookgo-logo.svg" alt="Look&Go" width={440} height={110}/><span>Le Dressing Privé IA</span><p>Les rendus IA sont des aides visuelles à la décision. Les résultats peuvent varier selon les photos et les vêtements.</p></footer><Link href="/connexion?mode=register" className="v2-mobile-cta">Scanner mon dressing <span>→</span></Link></>}
export function LookGoLandingV2(){return <main className="lookgo-v2"><Header/><Hero/><Story/><Experience/><Wardrobe/><Looks/><TryOn/><Offers/><Final/></main>}
