"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";

const closet="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1800&q=88";
const fashion="https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1600&q=88";

const Icon=({name}:{name:string})=><span className={`v2-icon i-${name}`} aria-hidden="true"/>;

function Header(){return <header className="v2-header"><Link href="#top" className="v2-logo"><Image src="/lookgo-logo.svg" alt="Look&Go" width={500} height={125}/></Link><nav><a href="#experience">L’expérience</a><a href="#dressing">Dressing</a><a href="#tryon">Try-On</a><a href="#offers">Offres</a></nav><Link href="/connexion?mode=register" className="v2-header-cta">Scanner mon dressing <span>→</span></Link></header>}

function Hero(){return <section id="top" className="v2-hero"><div className="v2-hero-bg"><Image src={closet} alt="Dressing privé contemporain" fill priority sizes="100vw"/></div><div className="v2-shade"/><div className="v2-scan-beam"/><div className="v2-detect d1"><i/><span>Blazer noir</span><b>98%</b></div><div className="v2-detect d2"><i/><span>Robe soirée</span><b>96%</b></div><div className="v2-detect d3"><i/><span>Chemise ivoire</span><b>94%</b></div><div className="v2-hero-content"><span className="v2-overline">LOOK&GO · LE DRESSING PRIVÉ IA</span><h1>Votre dressing<br/><em>vous connaît enfin.</em></h1><p>Une photo de votre penderie. Look&Go reconnaît vos pièces, vous les fait valider et compose des tenues avec ce que vous possédez déjà.</p><div className="v2-actions"><Link href="#experience" className="v2-primary">Entrer dans mon dressing <span>→</span></Link><a href="#story" className="v2-secondary">Voir comment ça marche</a></div></div><div className="v2-status"><span><Icon name="scan"/>12 pièces reconnues</span><span><Icon name="spark"/>3 looks prêts</span><span><Icon name="bag"/>0 achat inutile</span></div><a className="v2-scroll" href="#story"><i/>Découvrir</a></section>}

function Story(){return <section id="story" className="v2-story"><div className="v2-story-num">47</div><div><span className="v2-overline dark">LE PARADOXE DU DRESSING</span><h2>47 vêtements.<br/><em>Et toujours cette phrase.</em></h2><blockquote>« Je n’ai rien à me mettre. »</blockquote><p>Look&Go ne commence pas par vous vendre quelque chose. Il commence par révéler ce que vous avez déjà.</p></div></section>}

function Experience(){const [step,setStep]=useState(0);const steps=[{n:"01",icon:"camera",title:"Je photographie",text:"Une photo de penderie suffit pour commencer.",label:"PHOTO AJOUTÉE"},{n:"02",icon:"scan",title:"L’IA reconnaît",text:"Robes, vestes, hauts, bas et accessoires sont isolés.",label:"12 PIÈCES DÉTECTÉES"},{n:"03",icon:"check",title:"Je valide",text:"Rien n’entre dans votre dressing sans votre confirmation.",label:"9 VALIDÉES · 3 À VÉRIFIER"},{n:"04",icon:"spark",title:"Je reçois mes looks",text:"Travail, week-end, soirée : vos pièces reprennent vie.",label:"3 LOOKS CRÉÉS"}];return <section id="experience" className="v2-experience"><div className="v2-section-head"><span className="v2-overline">L’EXPÉRIENCE LOOK&GO</span><h2>De votre penderie<br/><em>à votre tenue.</em></h2><p>Pas de formulaire interminable. Votre dressing se construit visuellement, avec vous.</p></div><div className="v2-exp-shell"><div className="v2-exp-nav">{steps.map((s,i)=><button key={s.n} onClick={()=>setStep(i)} className={i===step?"active":""}><b>{s.n}</b><Icon name={s.icon}/><span>{s.title}</span></button>)}</div><div className="v2-exp-screen"><div className="v2-exp-photo"><Image src={closet} alt="Penderie analysée par Look&Go" fill sizes="(max-width:800px) 100vw, 55vw"/><div className={`v2-analysis a${step}`}><i/><i/><i/><i/></div><div className="v2-exp-label"><span>LOOK&GO VISION</span><strong>{steps[step].label}</strong></div></div><div className="v2-exp-copy"><span>{steps[step].n} / 04</span><Icon name={steps[step].icon}/><h3>{steps[step].title}</h3><p>{steps[step].text}</p><button onClick={()=>setStep((step+1)%4)}>Étape suivante →</button></div></div></div></section>}

function Wardrobe(){return <section id="dressing" className="v2-wardrobe"><div className="v2-wardrobe-copy"><span className="v2-overline">VOTRE DRESSING, PAS UN CATALOGUE</span><h2>Vos vêtements deviennent<br/><em>une matière à créer.</em></h2><p>L’IA retrouve les associations oubliées, remet les pièces peu portées dans la rotation et identifie ce qui manque vraiment.</p><div className="v2-metrics"><div><strong>34%</strong><span>noir dans votre dressing</span></div><div><strong>8</strong><span>pièces peu portées</span></div><div><strong>3,20€</strong><span>cost-per-wear moyen</span></div></div></div><div className="v2-wardrobe-ui"><div className="v2-ui-top"><span>MON DRESSING</span><b>38 pièces</b></div><div className="v2-clothes"><article><Icon name="hanger"/><b>Vestes</b><span>6 pièces</span></article><article><Icon name="dress"/><b>Robes</b><span>9 pièces</span></article><article><Icon name="shirt"/><b>Hauts</b><span>14 pièces</span></article><article><Icon name="bag"/><b>Accessoires</b><span>9 pièces</span></article></div><div className="v2-insight"><Icon name="spark"/><div><b>Une pièce dort depuis 83 jours.</b><span>Je peux créer 4 looks autour de votre blazer noir.</span></div><button>Créer les looks →</button></div></div></section>}

function Looks(){return <section className="v2-looks"><div className="v2-section-head light"><span className="v2-overline dark">VOTRE SEMAINE, DÉJÀ HABILLÉE</span><h2>Pas des inspirations.<br/><em>Vos tenues.</em></h2></div><div className="v2-look-row">{[["LUN · TRAVAIL","Réunion à 10h","94%"],["VEN · DÎNER","Terrasse à 20h","97%"],["SAM · WEEK-END","Déjeuner en ville","91%"]].map((x,i)=><article key={x[0]}><div className="v2-look-photo"><Image src={fashion} alt="Inspiration tenue Look&Go" fill sizes="(max-width:700px) 82vw, 30vw" style={{objectPosition:`${35+i*20}% center`}}/><span>{x[0]}</span></div><div><h3>{x[1]}</h3><span>Compatibilité style · {x[2]}</span><p>3 pièces de votre dressing</p><button>Voir le look →</button></div></article>)}</div></section>}

function TryOn(){return <section id="tryon" className="v2-tryon"><div className="v2-tryon-visual"><div className="v2-portrait"><Image src={fashion} alt="Aperçu mode pour Try-On" fill sizes="(max-width:800px) 100vw,50vw"/></div><div className="v2-try-card"><span>APERÇU IA</span><strong>Avant de commander</strong><i>↔</i></div></div><div className="v2-try-copy"><span className="v2-overline">TRY-ON PRIVÉ</span><h2>La pièce manque ?<br/><em>Voyez-la sur vous.</em></h2><p>Look&Go peut créer un aperçu haute fidélité pour vous aider à décider avec plus de confiance avant achat.</p><ul><li><Icon name="person"/>Morphologie comme référence</li><li><Icon name="face"/>Identité visuelle préservée comme objectif</li><li><Icon name="eye"/>Comparaison claire avant / aperçu</li></ul><small>Les rendus IA restent des aides visuelles. Le résultat réel peut varier selon la photo, la coupe et le vêtement.</small><a href="#offers" className="v2-primary">Découvrir Try-On <span>→</span></a></div></section>}

const offers=[{name:"Découverte",price:"0 €",desc:"Découvrez ce que votre dressing peut déjà faire.",items:["1 scan dressing","5 pièces validées","1 premier look"]},{name:"Pack Looks",price:"9,99 €",desc:"Une occasion. Trois réponses.",items:["3 looks personnalisés","Vos pièces en priorité","Occasion au choix"]},{name:"Premium",price:"9,99 €/mois",desc:"Votre dressing au quotidien.",items:["Dressing étendu","Looks hebdomadaires","Cost-per-wear & insights"],hot:true},{name:"VIP Try-On",price:"24,99 €/mois",desc:"Décidez avec plus de confiance.",items:["Try-On IA selon quotas","Looks avancés","Fonctions premium"]}];
function Offers(){return <section id="offers" className="v2-offers"><div className="v2-section-head"><span className="v2-overline dark">CHOISISSEZ VOTRE EXPÉRIENCE</span><h2>Commencez par votre dressing.<br/><em>Montez en puissance si ça vous aide.</em></h2></div><div className="v2-offer-grid">{offers.map(o=><article key={o.name} className={o.hot?"hot":""}>{o.hot&&<span className="v2-badge">LE CŒUR LOOK&GO</span>}<h3>{o.name}</h3><strong>{o.price}</strong><p>{o.desc}</p><ul>{o.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Link href="/connexion?mode=register">Commencer <span>→</span></Link></article>)}</div><p className="v2-note">Tarifs de lancement à tester pendant la bêta. Les services payants ne sont facturés qu’après leur activation réelle et les quotas IA pourront évoluer selon les coûts mesurés.</p></section>}

function Final(){return <><section className="v2-final"><span className="v2-overline">BÊTA PRIVÉE</span><h2>Ouvrez votre dressing.<br/><em>Look&Go s’occupe du reste.</em></h2><p>Faites partie des premières personnes à construire le Dressing Privé IA.</p><Link href="/connexion?mode=register" className="v2-primary">Demander mon accès <span>→</span></Link></section><footer className="v2-footer"><Image src="/lookgo-logo.svg" alt="Look&Go" width={440} height={110}/><span>Le Dressing Privé IA</span><p>Les rendus IA sont des aides visuelles à la décision. Les résultats peuvent varier selon les photos et les vêtements.</p></footer><Link href="/connexion?mode=register" className="v2-mobile-cta">Scanner mon dressing <span>→</span></Link></>}
export function LookGoLandingV2(){return <main className="lookgo-v2"><Header/><Hero/><Story/><Experience/><Wardrobe/><Looks/><TryOn/><Offers/><Final/></main>}
