"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
const closet="https://images.unsplash.com/photo-1520923179278-ee25e25e09e4?auto=format&fit=crop&w=1800&q=88";
const work="https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=1200&q=88";
const casual="https://images.unsplash.com/photo-1780566759959-73ce2af09f7c?auto=format&fit=crop&w=1200&q=88";
const evening="https://images.unsplash.com/photo-1674466922242-793e4092a9e2?auto=format&fit=crop&w=1200&q=88";
const tryon="https://images.unsplash.com/photo-1729202305341-d146fdea0a03?auto=format&fit=crop&w=1400&q=88";
const Icon=({name}:{name:string})=><span className={`v2-icon i-${name}`} aria-hidden="true"/>;
function Header(){return <header className="v2-header"><Link href="#top" className="v2-logo"><Image src="/lookgo-logo.svg" alt="Look&Go" width={500} height={125}/></Link><nav><a href="#experience">Fonctionnement</a><a href="#dressing">Dressing IA</a><a href="#looks">Looks</a><a href="#tryon">Try-On</a><a href="#offers">Tarifs</a><a href="#beta">Bêta</a></nav><Link href="/connexion?mode=register" className="v2-header-cta">Scanner mon dressing <span>→</span></Link></header>}
function Hero(){return <section id="top" className="v2-hero"><div className="v2-hero-bg"><Image src={closet} alt="Penderie remplie de vêtements" fill priority sizes="100vw"/></div><div className="v2-shade"/><div className="v2-scan-beam"/><div className="v2-detect d1"><span>Veste</span><b>98%</b></div><div className="v2-detect d2"><span>Robe</span><b>96%</b></div><div className="v2-detect d3"><span>Pantalon</span><b>94%</b></div><div className="v2-hero-content"><span className="v2-overline">LE DRESSING PRIVÉ IA</span><h1>Votre dressing<br/><em>devient intelligent.</em></h1><p>Scannez votre penderie, validez vos vêtements, recevez des looks personnalisés avec vos propres pièces et essayez virtuellement avant d’acheter.</p><div className="v2-actions"><Link href="#experience" className="v2-primary">Scanner mon dressing <span>→</span></Link><a href="#looks" className="v2-secondary">Voir un exemple</a></div><div className="v2-hero-pills"><span><Icon name="scan"/>Scan dressing IA</span><span><Icon name="check"/>Validation par vous</span><span><Icon name="hanger"/>Looks personnalisés</span><span><Icon name="spark"/>Try-On premium</span></div></div></section>}
function Problem(){return <section className="v2-problem"><div><span className="v2-overline dark">VOUS AVEZ DES VÊTEMENTS.</span><h2>Mais pas toujours<br/><em>une tenue.</em></h2></div><div className="v2-problem-grid"><article><Icon name="hanger"/><b>Penderie pleine</b><span>et aucune idée</span></article><article><Icon name="bag"/><b>Achats en double</b><span>sans s’en rendre compte</span></article><article><Icon name="scan"/><b>Retours colis</b><span>trop fréquents</span></article><article><Icon name="shirt"/><b>Pièces oubliées</b><span>jamais portées</span></article></div></section>}
function Experience(){const [step,setStep]=useState(0);const steps=[{n:"01",title:"Je photographie",text:"Une photo de votre vraie penderie suffit."},{n:"02",title:"L’IA reconnaît",text:"Les vêtements visibles sont isolés et classés."},{n:"03",title:"Je valide",text:"Vous gardez le contrôle sur chaque pièce."},{n:"04",title:"Je reçois mes looks",text:"Vos vêtements deviennent des tenues."}];const thumbs=[{src:work,t:"Travail",s:"94%"},{src:evening,t:"Dîner",s:"96%"},{src:casual,t:"Week-end",s:"92%"},{src:tryon,t:"Soirée",s:"95%"}];return <section id="experience" className="v2-experience"><div className="v2-section-head"><span className="v2-overline">COMMENT ÇA MARCHE</span><h2>Une photo. Une validation.<br/><em>Des looks.</em></h2></div><div className="v2-exp-shell"><div className="v2-exp-nav">{steps.map((s,i)=><button key={s.n} onClick={()=>setStep(i)} className={i===step?"active":""}><b>{s.n}</b><span>{s.title}</span></button>)}</div><div className="v2-journey-grid">{steps.map((s,i)=><article className={`v2-journey-phone ${i===step?"active":""}`} key={s.n} onClick={()=>setStep(i)}><div className="v2-phone-shell"><i className="v2-phone-notch"/><div className="v2-phone-screen"><Image src={closet} alt={s.title} fill sizes="(max-width:800px) 78vw,24vw"/><div className="v2-phone-overlay"/>{i===1&&<><i className="v2-mini-scan"/><i className="v2-mini-box b1"/><i className="v2-mini-box b2"/><i className="v2-mini-box b3"/></>}{i===2&&<div className="v2-validation-list"><span>Blazer noir <i>✓ Valider</i></span><span>Chemise ivoire <i>✓ Valider</i></span><span>Jean droit <i>Modifier</i></span><span>Robe noire <i>✓ Valider</i></span></div>}{i===3&&<div className="v2-look-stack">{thumbs.map(x=><span key={x.t} className="v2-look-mini"><Image src={x.src} alt={x.t} fill sizes="130px"/><b>{x.t}</b><i>{x.s}</i></span>)}</div>}<div className="v2-phone-title"><small>{i===0?"PHOTO PENDERIE":i===1?"LOOK&GO VISION":i===2?"VALIDATION CLIENTE":"LOOKS PERSONNALISÉS"}</small><strong>{i===0?"Votre vraie penderie":i===1?"12 pièces détectées":i===2?"9 pièces validées":"4 looks prêts"}</strong><p>{s.text}</p></div></div></div><div className="v2-journey-caption"><b>{s.title}</b><span>{s.text}</span></div><i className="v2-journey-arrow">→</i></article>)}</div><div className="v2-experience-foot"><button onClick={()=>setStep((step+1)%4)}>Voir l’étape suivante · {steps[(step+1)%4].title} →</button></div></div></section>}
function Wardrobe(){const features=[["hanger","Catégories automatiques"],["spark","Couleurs dominantes"],["person","Morphologie & colorimétrie"],["dress","Pièces peu portées"],["bag","Cost-per-wear & statistiques"],["check","Garder · Porter · Vendre"],["scan","Pièces manquantes à acheter"]];return <section id="dressing" className="v2-wardrobe"><div className="v2-wardrobe-copy"><span className="v2-overline">DRESSING INTELLIGENT</span><h2>Votre garde-robe devient<br/><em>un moteur de style.</em></h2><p>Look&Go commence par ce que vous possédez. L’achat n’intervient que lorsqu’il apporte une vraie utilité.</p></div><div className="v2-feature-rail">{features.map(([icon,label])=><article key={label}><Icon name={icon}/><span>{label}</span></article>)}</div></section>}
const looks=[{tag:"TRAVAIL",title:"Réunion à 10h",score:"94%",img:work},{tag:"DÎNER",title:"Dîner en ville",score:"96%",img:evening},{tag:"WEEK-END",title:"Brunch du dimanche",score:"92%",img:casual},{tag:"SOIRÉE",title:"Soirée cocktail",score:"95%",img:tryon}];
function Looks(){return <section id="looks" className="v2-looks"><div className="v2-looks-intro"><span className="v2-overline">DES TENUES CRÉÉES AVEC VOS VRAIES PIÈCES.</span><h2>Votre dressing.<br/><em>Vos possibilités.</em></h2><p>Chaque proposition commence par votre dressing avant de suggérer un achat.</p></div><div className="v2-look-row">{looks.map(x=><article key={x.tag}><div className="v2-look-photo"><Image src={x.img} alt={`${x.title} — exemple de tenue`} fill sizes="(max-width:700px) 82vw,24vw"/><span>{x.tag}</span></div><div><h3>{x.title}</h3><span>Score style · {x.score}</span><p>Pièces de votre dressing</p><button>Voir le look →</button></div></article>)}</div></section>}
function TryOn(){const [split,setSplit]=useState(50);return <section id="tryon" className="v2-tryon"><div className="v2-try-copy"><span className="v2-overline">TRY-ON IA · PREMIUM</span><h2>Essayez avant<br/><em>d’acheter.</em></h2><ul><li><Icon name="person"/>Même personne, même morphologie</li><li><Icon name="face"/>Identité conservée comme référence</li><li><Icon name="eye"/>Faites glisser pour comparer</li></ul><a href="#offers" className="v2-primary">Découvrir Try-On <span>→</span></a></div><div className="v2-tryon-visual"><div className="v2-compare" style={{"--split":`${split}%`} as React.CSSProperties}><div className="v2-compare-base"><Image src={tryon} alt="Photo de référence avant Try-On" fill sizes="(max-width:800px) 100vw,50vw"/><span>AVANT</span></div><div className="v2-compare-ai"><Image src={tryon} alt="Aperçu IA sur la même personne" fill sizes="(max-width:800px) 100vw,50vw"/><div className="v2-ai-blazer" aria-hidden="true"><i/><b/></div><span>APERÇU IA</span></div><div className="v2-compare-line"/><div className="v2-compare-handle">↔</div><input aria-label="Comparer avant et aperçu IA" type="range" min="8" max="92" value={split} onChange={e=>setSplit(Number(e.target.value))}/></div></div><aside className="v2-try-note"><span>Démo visuelle</span><p>La personne reste identique. Seule la tenue simulée change.</p><b>♕ Disponible en<br/>VIP Try-On</b></aside></section>}
const offers=[{name:"Scan Découverte",price:"0 €",items:["1 scan dressing","5 vêtements validés","1 look test","Diagnostic style basique"]},{name:"Pack Looks",price:"9,99 €",items:["3 looks personnalisés","Vos vêtements existants","Occasion au choix","Recommandations couleurs"]},{name:"Premium",price:"9,99 €/mois",items:["Dressing étendu","Looks hebdomadaires","Cost-per-wear","Alertes pièces manquantes","Favoris"],hot:true},{name:"VIP Try-On",price:"24,99 €/mois",items:["Try-On IA selon quotas","Looks avancés","Défilé privé expérimental","Conseiller IA prioritaire"]}];
function Offers(){return <section id="offers" className="v2-offers"><div className="v2-offers-title"><span className="v2-overline dark">COMMENCEZ GRATUITEMENT.</span><h2>Passez Premium quand<br/><em>votre dressing devient utile.</em></h2></div><div className="v2-offer-grid">{offers.map(o=><article key={o.name} className={o.hot?"hot":""}>{o.hot&&<span className="v2-badge">LE CŒUR LOOK&GO</span>}<h3>{o.name}</h3><strong>{o.price}</strong><ul>{o.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Link href="/connexion?mode=register">Commencer</Link></article>)}</div></section>}
function Beta(){const [done,setDone]=useState(false);return <section id="beta" className="v2-beta"><div><Image src="/lookgo-logo.svg" alt="Look&Go" width={440} height={110}/><span>Le Dressing Privé IA</span></div>{done?<p>Merci. Votre demande bêta est enregistrée dans cette démonstration.</p>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><input required placeholder="Prénom"/><input required type="email" placeholder="Email"/><select defaultValue=""><option value="" disabled>Style recherché</option><option>Chic</option><option>Casual</option><option>Minimaliste</option><option>Audacieux</option></select><select defaultValue=""><option value="" disabled>Problème principal</option><option>Je manque d’idées</option><option>J’achète trop</option><option>J’oublie mes vêtements</option></select><button>Demander mon accès bêta</button></form>}</section>}
function Footer(){return <><footer className="v2-footer v2-footer-complete"><div className="v2-footer-brand"><Image src="/lookgo-logo.svg" alt="Look&Go" width={420} height={105}/><p>Le Dressing Privé IA qui transforme votre garde-robe en moteur de style.</p></div><div><b>Look&Go</b><a href="#experience">Fonctionnement</a><a href="#dressing">Dressing IA</a><a href="#looks">Looks</a><a href="#tryon">Try-On</a></div><div><b>Informations</b><a href="#beta">Bêta privée</a><span>Confidentialité</span><span>Conditions d’utilisation</span><span>Contact</span></div><div className="v2-footer-bottom"><span>© 2026 Look&Go</span><p>Les rendus IA sont des aides visuelles à la décision. Les résultats peuvent varier.</p></div></footer><Link href="/connexion?mode=register" className="v2-mobile-cta">Scanner mon dressing <span>→</span></Link></>}
export function LookGoLandingV2(){return <main className="lookgo-v2"><Header/><Hero/><Problem/><Experience/><Wardrobe/><Looks/><TryOn/><Offers/><Beta/><Footer/></main>}
