"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useMemo, useRef, useState } from "react";
import { detectedWardrobe, generatedLooks, pricingPlans, WardrobeItem } from "@/lib/landing-mock";

function Header(){return <header className="lg-header"><Link href="#top" className="lg-brand"><Image src="/lookgo-logo.svg" alt="Look&Go" width={540} height={135} priority/></Link><nav><a href="#fonctionnement">Fonctionnement</a><a href="#dressing">Dressing IA</a><a href="#try-on">Try-On</a><a href="#tarifs">Tarifs</a><a href="#beta">Bêta</a></nav><Link href="#scan" className="lg-btn lg-btn-gold">Scanner mon dressing</Link></header>}

function Hero(){return <section id="top" className="lg-hero lg-shell"><div className="lg-hero-copy"><div className="lg-kicker">LOOK&GO · LE DRESSING PRIVÉ IA</div><h1>Votre dressing<br/><em>devient intelligent.</em></h1><p>Scannez votre penderie, validez vos vêtements, recevez des looks personnalisés avec vos propres pièces et essayez virtuellement avant d’acheter.</p><div className="lg-actions"><a href="#scan" className="lg-btn lg-btn-gold">Scanner mon dressing</a><a href="#fonctionnement" className="lg-btn lg-btn-ghost">Voir un exemple</a></div><div className="lg-proof"><span>Scan dressing IA</span><span>Validation cliente</span><span>Looks personnalisés</span><span>Try-On premium</span></div></div><div className="lg-hero-stage" aria-label="Démonstration visuelle du scan dressing"><div className="lg-stage-glow"/><div className="lg-closet"><div className="lg-rail"/><div className="lg-hanger h1"><i/><b>Blazer</b></div><div className="lg-hanger h2"><i/><b>Chemise</b></div><div className="lg-hanger h3"><i/><b>Robe</b></div><div className="lg-scan-line"/></div><div className="lg-phone"><div className="lg-phone-top">LOOK&GO</div><div className="lg-phone-photo"><span>SCAN EN COURS</span></div><div className="lg-phone-result"><strong>12 pièces détectées</strong><small>Prêtes à valider</small></div></div><div className="lg-float-card fc-one"><strong>12</strong><span>pièces détectées</span></div><div className="lg-float-card fc-two"><strong>3</strong><span>looks créés</span></div><div className="lg-float-card fc-three"><span>✓ Morphologie respectée</span></div><div className="lg-float-card fc-four"><span>+ Achat utile uniquement</span></div></div></section>}

function ProblemSection(){return <section className="lg-section lg-problem"><div className="lg-shell"><div className="lg-heading"><span>LE VRAI PROBLÈME</span><h2>Vous avez des vêtements.<br/><em>Mais pas toujours une tenue.</em></h2><p>Le matin, le problème n’est pas toujours le manque de vêtements. C’est le manque de visibilité, d’idées et de confiance dans les associations.</p></div><div className="lg-problem-grid">{[["01","Penderie pleine","Vous oubliez ce que vous possédez déjà."],["02","Achats en double","Une pièce ressemble parfois à trois autres déjà chez vous."],["03","Retours colis","Difficile d’imaginer la coupe avant réception."],["04","Pièces oubliées","Des vêtements restent invisibles pendant des mois."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}

function HowItWorks(){return <section id="fonctionnement" className="lg-section lg-how"><div className="lg-shell"><div className="lg-heading"><span>COMMENT ÇA MARCHE</span><h2>Une photo. Une validation.<br/><em>Des looks.</em></h2></div><div className="lg-flow"><article><b>01</b><div className="lg-flow-visual flow-photo"><span>PHOTO PENDERIE</span></div><h3>Photographiez votre penderie.</h3><p>Look&Go détecte robes, vestes, hauts, bas, chaussures et accessoires visibles.</p></article><div className="lg-flow-arrow">→</div><article><b>02</b><div className="lg-flow-visual flow-detect"><span>IA · 12 OBJETS</span><i/><i/><i/></div><h3>Validez ce que l’IA reconnaît.</h3><p>Vous confirmez, modifiez ou supprimez chaque pièce avant ajout au dressing numérique.</p></article><div className="lg-flow-arrow">→</div><article><b>03</b><div className="lg-flow-visual flow-look"><span>LOOK CRÉÉ</span><div>Blazer + chemise + jean</div></div><h3>Recevez vos tenues.</h3><p>Les looks tiennent compte de votre style, morphologie, occasion, couleurs et budget.</p></article></div></div></section>}

function WardrobeScanner(){const [items,setItems]=useState<(WardrobeItem & {status:"pending"|"valid"})[]>(detectedWardrobe.map(i=>({...i,status:"pending"})));const [uploaded,setUploaded]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const validCount=items.filter(i=>i.status==="valid").length;function remove(id:string){setItems(v=>v.filter(i=>i.id!==id))}function validate(id:string){setItems(v=>v.map(i=>i.id===id?{...i,status:"valid"}:i))}function edit(id:string){const name=window.prompt("Nom de la pièce",items.find(i=>i.id===id)?.name||"");if(name?.trim())setItems(v=>v.map(i=>i.id===id?{...i,name:name.trim()}:i))}return <section id="scan" className="lg-section lg-scanner"><div className="lg-shell lg-scanner-grid"><div><span className="lg-kicker">DÉMO INTERACTIVE</span><h2>Votre penderie.<br/><em>Déjà presque rangée.</em></h2><p>Testez le parcours MVP : importez une photo, puis validez les pièces reconnues. Cette démonstration n’envoie pas votre photo à un service IA.</p><input ref={inputRef} type="file" accept="image/*" hidden onChange={e=>setUploaded(Boolean(e.target.files?.length))}/><button className="lg-upload" onClick={()=>inputRef.current?.click()}><span>{uploaded?"✓ Photo prête":"＋"}</span><strong>{uploaded?"Photo ajoutée":"Choisir une photo de penderie"}</strong><small>{uploaded?"Simulation locale — aucune photo envoyée":"JPG, PNG ou photo mobile"}</small></button><div className="lg-scan-stats"><div><strong>{items.length}</strong><span>pièces détectées</span></div><div><strong>{validCount}</strong><span>validées</span></div></div></div><div className="lg-detected-list">{items.map(item=><article key={item.id} className={item.status==="valid"?"is-valid":""}><div className="lg-item-dot"/><div><strong>{item.name}</strong><span>{item.category} · {item.color} · {item.confidence}%</span></div><div className="lg-item-actions"><button onClick={()=>validate(item.id)}>{item.status==="valid"?"Validé":"Valider"}</button><button onClick={()=>edit(item.id)}>Modifier</button><button onClick={()=>remove(item.id)}>Supprimer</button></div></article>)}</div></div></section>}

function SmartWardrobe(){return <section id="dressing" className="lg-section lg-smart"><div className="lg-shell"><div className="lg-heading lg-heading-light"><span>DRESSING INTELLIGENT</span><h2>Votre garde-robe devient<br/><em>un moteur de style.</em></h2><p>Look&Go commence par ce que vous possédez. L’achat n’intervient que lorsqu’il apporte une vraie utilité.</p></div><div className="lg-smart-grid">{[["Catégories automatiques","Robes · vestes · hauts · bas · chaussures"],["Couleurs dominantes","Noir 34% · beige 18% · bleu 16%"],["Morphologie & colorimétrie","Des associations cohérentes avec votre profil"],["Pièces peu portées","Remettez vos vêtements oubliés dans la rotation"],["Cost-per-wear","Comprenez ce que chaque pièce vous coûte réellement"],["Garder · porter · vendre","Des recommandations utiles, pas du shopping forcé"],["Pièces manquantes","Achetez seulement ce qui complète vraiment le dressing"]].map((x,i)=><article key={x[0]} className={i===6?"lg-smart-wide":""}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>}

function LooksShowcase(){const [shown,setShown]=useState(false);const looks=useMemo(()=>shown?generatedLooks:generatedLooks.slice(0,1),[shown]);return <section className="lg-section lg-looks"><div className="lg-shell"><div className="lg-heading"><span>LOOKS PERSONNALISÉS</span><h2>Des tenues créées avec<br/><em>vos vraies pièces.</em></h2><p>Chaque proposition commence par votre dressing avant de suggérer un achat.</p></div><div className="lg-look-grid">{looks.map((look,index)=><article key={look.title}><div className={`lg-look-art look-${index+1}`}><span>{look.occasion}</span><div className="lg-look-silhouette"/></div><div className="lg-look-meta"><div><h3>{look.title}</h3><span>Score morpho-fit · {look.score}%</span></div><strong>{look.colors}</strong><ul>{look.items.map(item=><li key={item}>✓ {item}</li>)}</ul>{look.missing&&<div className="lg-missing">Pièce utile à compléter : <b>{look.missing}</b></div>}</div></article>)}</div>{!shown&&<button className="lg-btn lg-btn-dark" onClick={()=>setShown(true)}>Générer 3 looks de démonstration</button>}</div></section>}

function TryOnSection(){return <section id="try-on" className="lg-section lg-tryon"><div className="lg-shell lg-tryon-grid"><div className="lg-tryon-stage"><div className="lg-before"><span>VOTRE PHOTO</span></div><div className="lg-swipe">↔</div><div className="lg-after"><span>APERÇU TRY-ON</span></div><div className="lg-lock">VIP</div></div><div><span className="lg-kicker">TRY-ON IA · PREMIUM</span><h2>Essayez avant<br/><em>d’acheter.</em></h2><p>Lorsqu’une pièce manque, Look&Go peut générer un aperçu visuel haute fidélité pour vous aider à décider avec plus de confiance.</p><ul className="lg-checks"><li>Respect de la morphologie comme objectif de génération</li><li>Respect de la carnation et de l’identité visuelle</li><li>Comparaison avant / aperçu</li><li>Décision plus sereine avant commande</li></ul><small>Les rendus IA restent des aides visuelles : le résultat réel peut varier selon les photos, la coupe et le vêtement.</small><a href="#tarifs" className="lg-btn lg-btn-gold">Découvrir VIP Try-On</a></div></div></section>}

function PricingSection(){return <section id="tarifs" className="lg-section lg-pricing"><div className="lg-shell"><div className="lg-heading"><span>OFFRES LOOK&GO</span><h2>Commencez gratuitement.<br/><em>Passez Premium quand votre dressing devient utile.</em></h2></div><div className="lg-price-grid">{pricingPlans.map(plan=><article key={plan.name} className={plan.featured?"featured":""}>{plan.featured&&<span className="lg-popular">LE CŒUR LOOK&GO</span>}<h3>{plan.name}</h3><strong>{plan.price}</strong><p>{plan.subtitle}</p><ul>{plan.features.map(f=><li key={f}>✓ {f}</li>)}</ul><Link href="/connexion?mode=register" className={plan.featured?"lg-btn lg-btn-gold":"lg-btn lg-btn-dark"}>Commencer</Link></article>)}</div><p className="lg-pricing-note">Tarifs de lancement à tester pendant la bêta. Les fonctions payantes ne sont facturées qu’après activation réelle du paiement. Les limites IA peuvent évoluer selon les coûts réels mesurés.</p></div></section>}

function BetaSection(){const [sent,setSent]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)}return <section id="beta" className="lg-section lg-beta"><div className="lg-shell lg-beta-grid"><div><span className="lg-kicker">BÊTA PRIVÉE</span><h2>Rejoignez les premières<br/><em>utilisatrices Look&Go.</em></h2><p>Nous ouvrons la bêta à un petit groupe de testeuses pour construire le dressing IA le plus utile possible.</p></div>{sent?<div className="lg-beta-success"><span>✓</span><h3>Demande préparée.</h3><p>Cette démo valide le parcours UI. La connexion à la base bêta sera activée avec le backend définitif.</p><Link href="/connexion?mode=register" className="lg-btn lg-btn-gold">Créer mon profil bêta</Link></div>:<form onSubmit={submit}><label>Prénom<input name="firstName" required placeholder="Votre prénom"/></label><label>Email<input name="email" type="email" required placeholder="vous@exemple.fr"/></label><label>Style recherché<select name="style" defaultValue=""><option value="" disabled>Choisir</option><option>Chic</option><option>Casual</option><option>Minimaliste</option><option>Glamour</option><option>Streetwear</option><option>Je veux le découvrir</option></select></label><label>Votre problème principal<select name="problem" defaultValue=""><option value="" disabled>Choisir</option><option>Je ne sais pas quoi mettre</option><option>J’achète trop</option><option>Je veux essayer avant achat</option><option>Je veux mieux organiser mon dressing</option></select></label><button className="lg-btn lg-btn-gold" type="submit">Demander mon accès bêta</button></form>}</div></section>}

function Footer(){return <footer className="lg-footer"><div className="lg-shell"><div><Image src="/lookgo-logo.svg" alt="Look&Go" width={420} height={105}/><p>Le Dressing Privé IA</p></div><nav><a href="#fonctionnement">Fonctionnement</a><a href="#dressing">Dressing IA</a><a href="#try-on">Try-On</a><a href="#tarifs">Tarifs</a></nav><p className="lg-legal">Les rendus IA sont des aides visuelles à la décision. Les résultats peuvent varier selon la qualité des photos et les vêtements.</p></div></footer>}

export function LookGoLanding(){return <main className="lookgo-2026"><Header/><Hero/><ProblemSection/><HowItWorks/><WardrobeScanner/><SmartWardrobe/><LooksShowcase/><TryOnSection/><PricingSection/><BetaSection/><Footer/></main>}
