"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";
import { BetaProfile, clearBetaProfile, readBetaProfile, saveBetaProfile } from "@/lib/beta-profile";
import { BetaMediaKey, readBetaMedia, saveBetaMedia } from "@/lib/beta-media";
import "./profil.css";

function PhotoCard({kind,label,name,onSaved}:{kind:BetaMediaKey;label:string;name?:string;onSaved:(name:string)=>void}){
 const [url,setUrl]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{let current="";readBetaMedia(kind).then(blob=>{if(blob){current=URL.createObjectURL(blob);setUrl(current)}});return()=>{if(current)URL.revokeObjectURL(current)}},[kind,name]);
 async function change(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setSaving(true);await saveBetaMedia(kind,f);onSaved(f.name);setSaving(false)}
 return <article className="reference-photo-card"><div className="reference-photo-frame">{url?<img src={url} alt={label}/>:<div className="reference-photo-empty">Aucune photo enregistrée</div>}</div><div className="reference-photo-copy"><span>{label}</span><strong>{name||"À ajouter"}</strong><label className="reference-photo-button"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={change}/>{saving?"Enregistrement…":url?"Remplacer":"Ajouter"}</label></div></article>
}

export default function ProfilPage(){
 const [p,setP]=useState<BetaProfile|null>(null);
 useEffect(()=>setP(readBetaProfile()),[]);
 if(p===null) return <main className="account-page"/>;
 if(!p.email&&!p.pseudo) return <main className="account-page"><section className="account-shell"><div className="account-content"><div className="profile-status"><div><span>MODE BÊTA</span><h2>Aucun profil sur cet appareil.</h2><p>Créez un profil de test pour commencer le parcours Look&Go.</p></div><Link href="/connexion?mode=register">Démarrer →</Link></div></div></section></main>;
 const styles=(p.styles||[]).join(" · ")||"À définir"; const colors=(p.likedColors||[]).join(" · ")||"À définir";
 const updatePhoto=(field:"portraitName"|"fullName",name:string)=>{const next={...p,[field]:name};setP(next);saveBetaProfile({[field]:name})};
 return <main className="account-page"><header className="account-header"><Link href="/" className="account-logo">LOOK&GO</Link><div><span>{p.email}</span><button onClick={()=>{clearBetaProfile();location.href="/"}}>Quitter la bêta</button></div></header><section className="account-shell"><aside><p>MON ESPACE BÊTA</p><h1>Bonjour<br/><em>{p.pseudo||"vous"}</em></h1><nav><Link href="/profil" className="active">Mon profil</Link><Link href="/inscription">Modifier mes informations</Link><Link href="/inscription/analyse">Mes 3 looks</Link><Link href="/inscription/analyse">Try-On</Link></nav></aside><div className="account-content"><div className="profile-status"><div><span>PROFIL LOOK&GO</span><h2>{p.complete?"Votre profil bêta est prêt.":"Continuons votre profil."}</h2><p>{p.complete?"Vos préférences et vos photos de référence sont conservées sur cet appareil pour les essais bêta.":"Complétez les étapes pour préparer vos recommandations."}</p></div><Link href={p.complete?"/inscription/analyse":"/inscription"}>{p.complete?"Voir mes looks":"Reprendre"} →</Link></div><section className="reference-photos"><div className="reference-photos-head"><span>PHOTOS DE RÉFÉRENCE</span><h2>Portrait & silhouette</h2><p>Vérifiez ici les photos utilisées comme références. Vous pouvez les remplacer à tout moment.</p></div><div className="reference-photos-grid"><PhotoCard kind="portrait" label="PORTRAIT" name={p.portraitName} onSaved={n=>updatePhoto("portraitName",n)}/><PhotoCard kind="fullBody" label="PLEIN PIED" name={p.fullName} onSaved={n=>updatePhoto("fullName",n)}/></div></section><div className="account-grid"><article><span>IDENTITÉ</span><strong>{p.pseudo||"À compléter"}</strong><p>{p.email}</p></article><article><span>MENSURATIONS</span><strong>{p.height?`${p.height} cm`:"À compléter"}</strong><p>{p.weight?`${p.weight} kg`:"Poids à renseigner"}</p></article><article><span>STYLE</span><strong>{p.budgetMode||"À définir"}</strong><p>{p.budget?`Budget tenue : ${p.budget} €`:"Budget à renseigner"}</p></article><article><span>TAILLES</span><strong>{p.topSize||"—"} / {p.bottomSize||"—"}</strong><p>Pointure {p.shoeSize||"—"}</p></article></div><div className="account-grid"><article><span>STYLES AIMÉS</span><strong>{styles}</strong><p>Base des recommandations bêta</p></article><article><span>COULEURS</span><strong>{colors}</strong><p>À éviter : {(p.avoidColors||[]).join(" · ")||"aucune"}</p></article></div><div className="account-note"><strong>MVP BÊTA</strong><p>Les photos sont désormais conservées dans le navigateur et restent modifiables depuis ce profil. La génération Try-On IA doit encore être raccordée au fournisseur de génération avant d’afficher de vraies images générées.</p></div></div></section></main>
}
